### ISSUE TITLE
Do a video screenshot with the actual size of the video

### ISSUE THREAD

**Issue by LukasThyWalls** [gurumukhi/youtube-screenshot#11]
Hi

It's a simple but useful addon!

However i saw something (other people in the addons.mozilla.org page talk about this too) and it's not mentioned here, so i will do it.

~The addon actually does a screenshot of the video at the size you are seeing it. If you are seeing a video at 1080p, it doesn't produce a screenshot with 1080 pixels of height, it does a smaller screenshot depending if you are seeing the video in normal mode, cinema mode or full screen, and it does the screenshot in the view size. The only option to see a 1080 pixels screenshot, for example, is doing it when you have a 1080p monitor and you are seen it in fullscreen.~

Maybe is something inherited of how the addon works or a limitation of Firefox and can't be done in other way, in that case should be noted somewhere.

And maybe is related to https://github.com/gurumukhi/youtube-screenshot/issues/1

Thanks in advance!

**Comment by LukasThyWalls** [comment]
I wanted to deleted the issue, because i found i misinterpreted the behaviour.

I was thinking it does the screenshot with the actual size of the viewport, but i'm wrong. With one computer (with a monitor of 1440x900) the screenshot size seems equal how it's the viewport (mid size when is player is normal, larger when its in cinema mode, and 1440x900 when i'm seeing it in fullscreen). But in other computer with a 1920x1080 screen, the screenshot in fullscreen is 1536x864. I don't know exactly from where takes this size but it's how it works for me.

Thanks.

**Comment by gurumukhi** [comment]
Closing this in favor of #1. Thanks :-)
