### ISSUE TITLE
What's the license for this project?

### ISSUE THREAD

**Issue by HamletDuFromage** [gurumukhi/youtube-screenshot#13]
Hello, 
I've used your code and slightly modified it to use with Enhancer for Youtube and it works great. I'd like to publish my code in a git gist (for my own mostly) but I couldn't find the license you're using, and I wouldn't want to infringe on your freedoms

**Comment by gurumukhi** [comment]
I am happy to hear you find it useful. Feel free to use/modify the code as
you wish.

Also I haven't included license info in any of my code bases, I should have
done it. If you want, you can raise a PR to this or other projects of mine
with license info somewhere. I haven't done extensive research on selecting
the license, I have done all open source work with spirit of sharing it
with others I think MIT license is good enough. Feel free to share if you
have any recommendations for me on this. Thanks 😊
