### ISSUE TITLE
Please add a shortcut key

### ISSUE THREAD

**Issue by tanvir1414** [gurumukhi/youtube-screenshot#15]
Others screenshot app has shortcut key. Please implement a shortcut shift+a. Thanks.

**Comment by gurumukhi** [comment]
Very good suggestion. Thanks.

**Comment by joggee-fr** [comment]
I have recently tested to add an hard-coded shortcut (shift+a) and it does not seems to be a big change.
It may be a bit less easy if the shortcut can be configured through add-on preferences.

@gurumukhi, what do you think of an hard-coded shortcut? At least, we can allow to enable or disable it through preferences.

**Comment by gurumukhi** [comment]
Ya it sounds like the best option - hard-coded shortcut + ability to disable it (or for now we can just keep it disabled, and interested users can enable it).

**Comment by joggee-fr** [comment]
Integrated in PR #48.
@gurumukhi, you can close this issue now.
By the way, you can also update the preferences screenshot and description on the Mozilla addon page.

**Comment by gurumukhi** [comment]
Yes, true. Will do that. Thanks :)
