### ISSUE TITLE
Save screenshots as PNGs

### ISSUE THREAD

**Issue by RyutoSetsujin** [gurumukhi/youtube-screenshot#16]
PNGs are just better than jpegs :) It'd be even better if you added an option to switch between different file formats

**Comment by developer-irfan** [comment]
@RyutoSetsujin assign me this task. i will code in order that can save ss as png.

**Comment by gurumukhi** [comment]
Thanks @developer-irfan , while you are at it, you can also look into two other improvement requests - shortcut key (https://github.com/gurumukhi/youtube-screenshot/issues/15) & copy to clipboard (https://github.com/gurumukhi/youtube-screenshot/issues/8).

Thanks,
Ram

**Comment by RyutoSetsujin** [comment]
Would it maybe be possible for this to get pushed to the Firefox extension as well as possibly the option to press the P key to take screenshots?

**Comment by joggee-fr** [comment]
@RyutoSetsujin, please take a look and add a review to my PR #18 if you can.

**Comment by gurumukhi** [comment]
This is fixed via https://github.com/gurumukhi/youtube-screenshot/pull/18, new version of the add-on is available with the option to save as PNG - https://addons.mozilla.org/en-US/firefox/addon/youtube-screenshot-button/. Thanks @joggee-fr for fixing this.

@developer-irfan, @RyutoSetsujin you can work on other open issues if you want to contribute to the project (e.g. adding shortcut key is still pending). Let me know if you need anything from my side.
