### ISSUE TITLE
Call once guard in initialization?

### ISSUE THREAD

**Issue by joggee-fr** [gurumukhi/youtube-screenshot#19]
Do we really need this call once guard:
https://github.com/gurumukhi/youtube-screenshot/blob/8b1e32eae89cdb7a44d924e079207e5e9c388d91/content_script.js#L69 ?
I am very new to WebExtension dev but trying to improve this useful one. I am in the good way to fix an issue when the add-on is loaded opening the YouTube homepage, not directly a video page. However, as the patch is done in the initialization phase, I wonder if it is useful to keep this guard.

Thanks.

**Comment by gurumukhi** [comment]
This guard makes sure duplicate button is not added if the init method is
called again on same page where button is already added (there could be
various scenarios when this might happen).

**Comment by joggee-fr** [comment]
Thanks @gurumukhi.
I tried to reproduce such a case but was not able to do in "normal" cases. I encountered such a behavior when reloading the add-on in `about:debugging` of Firefox, but it is surely not a typical use case. Furthermore, the guard is not working in such a case.
IMHO, if the whole script is reloaded, the `initCalled` variable is set to `false`again and screenshot button is consequently duplicated.
If you can give me a way to reproduce, I would be happy to try.

**Comment by gurumukhi** [comment]
You might be right. I think we should get rid of this.

Also, see if you can look into issues #15 & #8 too. Then I will merge all
PRs together and republish the add-on.

**Comment by joggee-fr** [comment]
I am preparing a new PR to get rid of this unneeded guard and fix incorrect behavior when starting at YouTube homepage.
I am not very sure I can take a look at issues #15 and #8 soon. You can already review my PRs #17 and #18 😄, for different topics.

**Comment by joggee-fr** [comment]
@gurumukhi,
is the project still alive?

**Comment by gurumukhi** [comment]
Yes it is.

Should I merge your PRs now? Sorry for delay.

**Comment by gurumukhi** [comment]
Merged two PRs, can you please help me resolve this conflict 
https://github.com/gurumukhi/youtube-screenshot/pull/18/conflicts ?

**Comment by joggee-fr** [comment]
Thanks for the merge @gurumukhi. I have just updated the PR #18 to fix the conflicts.
Let me know if you wish me to change something.

By the way, this issue #19 is now fixed for me.
