### ISSUE TITLE
Doesn't work in Khan academy videos

### ISSUE THREAD

**Issue by aminya** [gurumukhi/youtube-screenshot#2]
For example, in this webpage, if you play a youtube video no button is shown
https://www.khanacademy.org/math/statistics-probability/probability-library/conditional-probability-independence/v/calculating-conditional-probability?modal=1

**Comment by gurumukhi** [comment]
let me see if i can get this working.

**Comment by gurumukhi** [comment]
The addon is built only for YouTube, khanacademy is not using YouTube to stream its videos so its expected not to work there. Closing the issue, feel free to reopen if required.
