### ISSUE TITLE
Check compatibility with other addons like Enhancer for Youtube.

### ISSUE THREAD

**Issue by gurumukhi** [gurumukhi/youtube-screenshot#24]
Some users reported conflict with Enhancer and other addons. 

More at https://addons.mozilla.org/en-US/firefox/addon/youtube-screenshot-button/reviews/.

**Comment by joggee-fr** [comment]
I have just tested compatibility with Enhancer for Youtube add-on and don't have observed an issue yet.
This add-on is interesting and includes a screenshot feature. However, it sadly does not seem to be an open source project.

**Comment by gurumukhi** [comment]
Alright, I will close this issue as of now. This can be re-opened if anyone reports any compatibility related issue. Thanks @joggee-fr :)
