### ISSUE TITLE
Movies/TV/any other purchased content makes a black screen instead of a screenshot

### ISSUE THREAD

**Issue by thepwrtank18** [gurumukhi/youtube-screenshot#27]
I don't know if this issue is fixable due to Widevine DRM, but I just thought to put it here.

**Comment by joggee-fr** [comment]
Confirmed.
At least, we may take a look at `document.querySelector('video').mediaKeys`, a non-null value seems to indicate the media is DRM-protected (from [here](https://stackoverflow.com/questions/66249367/how-to-detect-whether-a-html-video-is-drm-protected-with-javascript-in-chrome)).
Not trying to save the screenshot in this case and alerting through a notification may be a better experience.

**Comment by thepwrtank18** [comment]
#28

**Comment by gurumukhi** [comment]
Thanks @thepwrtank18 & @joggee-fr, I will publish updated version.
