### ISSUE TITLE
Colon (:) in filename

### ISSUE THREAD

**Issue by joggee-fr** [gurumukhi/youtube-screenshot#29]
I have just figured the colon character is used to separate timestamp in filename. Testing the extension with Firefox on macOS, it seems the character is simply replaced by a whitespace in this case.
After a bit of research, colon in filename is also forbidden in the Windows world. It should be no worry for Linux however 😃 .

To have a coherent filename through all systems, it may be better to use an other separator e.g. [this Chrome extension](https://github.com/FutureMillennium/Screenshot-YouTube/blob/46bf9d2407f570417c9ddfc5be3424edabb647d4/extension/page.js#L50) uses hyphen / minus symbol. What do you think about it ?

**Comment by gurumukhi** [comment]
Great suggestion, we should fix this. Thanks for pointing it out :)

**Comment by joggee-fr** [comment]
Separator has been changed in (merged) PR #30.
