### ISSUE TITLE
Doesn't work while using Enhancer for YouTube by Maxime RF 

### ISSUE THREAD

**Issue by Bonclove** [gurumukhi/youtube-screenshot#3]
Don't know how possible it is to have both addons working at the same time but I thought it'd be worth noting.

**Comment by gurumukhi** [comment]
will check this

**Comment by gurumukhi** [comment]
This works fine for me, can you please check this again with updated version of the extension? Closing this for now, if you still see this as issue please reopen this with more info (e.g. whether the button is not working at all or its saving blank image).
