### ISSUE TITLE
Now not working

### ISSUE THREAD

**Issue by daps2401** [gurumukhi/youtube-screenshot#33]

**Comment by gurumukhi** [comment]
Thanks for reporting the issue. Can you please provide more details to reproduce it? We made few major changes recently, it could give some surprises. @joggee-fr can you please try to reproduce the issue?

**Comment by daps2401** [comment]
It seems to have been linked to an update not having been applied as it's now working fine with an update dated today.
Sorry, I couldn't figure how to delete my previous comment!

**Comment by joggee-fr** [comment]
> It seems to have been linked to an update not having been applied as it's now working fine with an update dated today. Sorry, I couldn't figure how to delete my previous comment!

@daps2401, good to know it is working. Don't worry for your first comment, the issue will just be closed with no fix needed.

**Comment by gurumukhi** [comment]
Oh great, thanks 👍
