### ISSUE TITLE
Please update the extension that give file output name (time) from hour-minute-seconds (1-01-52) to minute seconds (61 52)

### ISSUE THREAD

**Issue by tanvir1414** [gurumukhi/youtube-screenshot#40]
Previously I have used this extension that gives time in minutes second format not in hour minute second format. Previously I used to take hundred of screenshots from a video and it automatically sorted by file name including the ones which have been taken one hour two hours time slot on the video. Now one hour screenshot comes after only 0 minutes. Now two Hours screenshot come after 2 minutes. The whole add-on is a mess. 
Now I have to make a sub-folder for each hours of video. It is a tedious process. I don't like it. Or I have to sometimes sort it by date modified which is sometimes not practical.
Showing output: File name hour-minute-seconds **Ex=> File Name 1-01-52**
Expected output: File name minute seconds **Ex=>File Name 61 52**

I use this addons for my note taking. I will give you five star if you give me the older add-ons which only give time minute second format.
Or at least give the option to download the older add-ons that gives the time in (minute second) format.

**Comment by joggee-fr** [comment]
Hi @tanvir1414,

I am the one who proposed the commit to add hours in timestamp, just [here](https://github.com/gurumukhi/youtube-screenshot/pull/30/commits/51ec786b0e17601f12f604dc87847b450e720a46). I can understand your point of view. However, my main motivation for this modification was resulting from live videos with very high number of minutes.

If this is really an issue for you, I can propose right now at least two solutions:
- propose a PR to add an option in the addon preferences to manage timestamp the old way or may be better a fully customizable title format ;
- clone the repository, check out the commit before my change and install it manually for you ;
- or you may also just revert my commit from master branch and install it again manually for you.

**Comment by tanvir1414** [comment]
How to build the extension? I download the file and then zip it and select from file but not able to be successful. It says the add-ons file is corrupt. Actually I have no idea to build Firefox extension. I see some YouTube videos that does not work either. Any help will be appreciated.

**Comment by tanvir1414** [comment]
How to build the extension? I download the file and then zip it and select from file but not able to be successful. It says the add-ons file is corrupt. Actually I have no idea to build Firefox extension. I have idea how to revert changes so that is not an issue. I see some YouTube videos that does not work either about Firefox extension. Any help will be appreciated.

**Comment by tanvir1414** [comment]
This one sounds great.
propose a PR to add an option in the addon preferences to manage timestamp the old way or may be better a fully customizable title format.

**Comment by joggee-fr** [comment]
> How to build the extension? I download the file and then zip it and select from file but not able to be successful. It says the add-ons file is corrupt. Actually I have no idea to build Firefox extension. I have idea how to revert changes so that is not an issue. I see some YouTube videos that does not work either about Firefox extension. Any help will be appreciated.

This extension does not need to be build. Based on the [following instructions](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/wiki/Firefox-installation-guide), it seems you try to install it correctly.
Maybe [these rules](https://extensionworkshop.com/documentation/publish/package-your-extension/) to package the extension have the detail you missed.

@gurumukhi, do you do something special for the package to be submitted to Mozilla?

**Comment by gurumukhi** [comment]
@tanvir1414 Try instructions given at https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

1. open Firefox
2. enter "about:debugging" in the URL bar
3. click "This Firefox"
4. click "Load Temporary Add-on"
5. open the extension's directory and select any file inside the extension, or select the packaged extension (.zip file).

Make sure you have disabled/uninstalled the currently published version of the addon before trying to load the old version.

Thanks :)

**Comment by tanvir1414** [comment]
I don't know the manifest.json is the only file required to load all the files. I am successfully able to load the extension. Thanks anyway.

**Comment by tanvir1414** [comment]
I tried your method but extension did not persist. After every restart, extension is gone. 
I suggest you append (0-) for 0 hour .
The expected output should be **File Name 0-01-52** not **File Name 01-52**. 
In this way, file name is constant for sorted by file name.

If possible, please release the xpi file of old version maybe in release section. This way I don't have to deal with restart hell of loading extension every time when I have to use it.
@gurumukhi 
I personally believe this is a easy problem to solve to append (**0-**) for first hour and release the update of extension in Firefox add-ons store.

**Comment by tanvir1414** [comment]
Elaborative Example,
Showing output: File name hour-minute-seconds Ex=> **File Name 01-52**
Expected output: File name hour-minute-seconds Ex=> **File Name 0-01-52**

**Comment by joggee-fr** [comment]
> I suggest you append (0-) for 0 hour . The expected output should be **File Name 0-01-52** not **File Name 01-52**. In this way, file name is constant for sorted by file name.

It seems a reasonable change for me. Could you propose such a PR to always add hour to filename?

**Comment by gurumukhi** [comment]
@tanvir1414 thanks for your suggestion of keeping old releases open. You can use the following links to install previous versions:

https://addons.mozilla.org/firefox/downloads/file/1174220/youtube_screenshot_button-1.0.0.xpi
https://addons.mozilla.org/firefox/downloads/file/3605792/youtube_screenshot_button-1.4.0.xpi
https://addons.mozilla.org/firefox/downloads/file/4008578/youtube_screenshot_button-2.0.0.xpi
https://addons.mozilla.org/firefox/downloads/file/4047160/youtube_screenshot_button-2.1.0.xpi

Hope this will be useful for you. We will also incorporate other suggestions of your in future releases. 

Thanks again :)

- Ram
