### ISSUE TITLE
Issue with Short videos

### ISSUE THREAD

**Issue by gurumukhi** [gurumukhi/youtube-screenshot#43]
Received following review (https://addons.mozilla.org/en-US/firefox/addon/youtube-screenshot-button/reviews/1971184/)

"The add-on is very beautiful. It works well with regular videos, but with short videos, it does not work at all. When I try to press, it does not respond to me. All it does is stop the video only. I hope that this problem will be solved because of this. I hope for a quick response."

**Comment by gurumukhi** [comment]
Hi @joggee-fr, can you also try to reproduce this issue?

**Comment by joggee-fr** [comment]
@gurumukhi 
Issue confirmed. The YouTube interface must have changed and the "Screenshot" button for reels / shorts is not clickable anymore. When simulating a click through the JS console, the action is OK and screenshot is saved as usual. It is really a CSS / HTML issue with the current YouTube interface. I will try to check it soon.

**Comment by gurumukhi** [comment]
Thanks for fixing the issue @joggee-fr, I have uploaded new version with the fix.
