### ISSUE TITLE
"Download file" option disappears after selecting "Copy to clipboard"

### ISSUE THREAD

**Issue by joggee-fr** [gurumukhi/youtube-screenshot#46]
Up-to-date Firefox 114.0.2 (64-bit) on macOS.
In the options page (preferences), when I select "Copy to clipboard" option, the image format selector is hidden as intended but I am not able to select back "Download file" option. Am I the only one to reproduce this issue?

<img width="518" alt="image" src="https://github.com/gurumukhi/youtube-screenshot/assets/77963242/fe55aaa6-ce80-4fd2-9215-93dcaef0ced4">

**Comment by joggee-fr** [comment]
Leaving user the choice to select JPEG or PNG format for "Copy to clipboard" avoids this issue. Such a feature were asked in issue #36.

**Comment by gurumukhi** [comment]
I am able to reproduce this issue. Once user selects 'Copy to clipboard', the dropdown's height decreases and I see only one option initially. To select 'Download file' option use has to scroll, which is not at all expected.

**Comment by gurumukhi** [comment]
Anyways, I was thinking to use radio buttons here instead of list. Its the time to move to radio button I think. @joggee-fr can you take care of this? Also, see if we can close this PR along with fixing this issue - https://github.com/gurumukhi/youtube-screenshot/pull/31.

**Comment by joggee-fr** [comment]
> I am able to reproduce this issue. Once user selects 'Copy to clipboard', the dropdown's height decreases and I see only one option initially. To select 'Download file' option use has to scroll, which is not at all expected.
Nice catch that scrol is needed to show the download option. So I think it is a "page" height issue. However, let's be coherent and use radio buttons for all options. I will propose a PR to do so very soon.

**Comment by joggee-fr** [comment]
> Anyways, I was thinking to use radio buttons here instead of list. Its the time to move to radio button I think. @joggee-fr can you take care of this? Also, see if we can close this PR along with fixing this issue - #31.

For applying your PR #31 or not, it's up to you. I just don't think it is important to edit a lot default style here.

**Comment by joggee-fr** [comment]
Work around with PR #47.
