### ISSUE TITLE
Install Addon Manually

### ISSUE THREAD

**Issue by lookatdons** [gurumukhi/youtube-screenshot#5]
How to install this addon manually? Since there's no xpi file in it. Or is there any option to save the screenshot as .jpg? If none then I have to install it manually after editing the code from .png to .jgp. Please advice. Thank you.

**Comment by gurumukhi** [comment]
Hi @lookatdons , you can find instructions for temporarily loading extensions using source code at https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/. Feel free to add option to download file in multiple extensions to the add-on. Thanks!

**Comment by gurumukhi** [comment]
Closing as solution is provided in previous comment, feel free to reopen if required.
