### ISSUE TITLE
User review issue

### ISSUE THREAD

**Issue by gurumukhi** [gurumukhi/youtube-screenshot#54]
As per review - https://addons.mozilla.org/en-US/firefox/addon/youtube-screenshot-button/reviews/1590845/ 

1
Even with the video quality set to 1080p, the size of the screenshot was not 1920x1080.
The size of the screenshot seems to be determined by the actual size of the video on the screen, not the quality setting.
Note that in the case of a similar extension for Chrome, the size of screenshot is determined by the quality of the video, not the size of the video displayed on the screen.

2
Conflicts with Enhancer for YouTube.
If Enhancer for YouTube is enabled, the screenshot button will not appear.

**Comment by joggee-fr** [comment]
This review has been published 3 years ago with a slightly different version of the addon.
For example, PR #21 fixes point 1 about video / screenshot resolution.
Point 2 was issue #24. I am not a daily user of this Enhancer for Youtube addon, so I don't know if it is still an issue.

**Comment by gurumukhi** [comment]
Ok lets close it for now. If anyone faces any issues due to conflict with other addon they can reopen it or raise another issue. Thanks :)
