### ISSUE TITLE
Option to choose save location every time screenshot is taken

### ISSUE THREAD

**Issue by probablytukars** [gurumukhi/youtube-screenshot#58]
With relevance to #37, would it be possible to add an option so that I can choose where to save a screenshot every time I take one (with the dialog that appears)

Thank you!

**Comment by PRIXYY** [comment]
The new version now comes with an option to select where to save the screenshot and I have tested it and it works completely fine.

**Comment by gurumukhi** [comment]
Thanks, closing the issue. Feel free to comment if required.
