### ISSUE TITLE
Filename ends with ".png" but is JPEG file

### ISSUE THREAD

**Issue by the-only-felix-mueller** [gurumukhi/youtube-screenshot#7]
When I click "Screenshot" on a Youtube video a file-save-dialog opens where I can save the file. The name of the file ends with ".png" but it's really a ".jpeg" file.

![youtube-screenshot-png-jpg](https://user-images.githubusercontent.com/67778680/86902819-c494a400-c10e-11ea-9a42-3a504b08ba84.png)  
(That's German, but it shows the filename in bold and the true filetype below.)

I suppose you should change the filename to end with ".jpeg".

**Comment by gurumukhi** [comment]
Thanks for reporting this, I have fixed the issue and published new version. Closing this issue, feel free to reopen if required.

Ref: https://github.com/gurumukhi/youtube-screenshot/pull/9
